<?php

namespace AppBundle\Repository;

/**
 * VisitDayHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitDayHourRepository extends \Doctrine\ORM\EntityRepository
{
}
