<?php

namespace AppBundle\Repository;

/**
 * VisitingDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitingDayRepository extends \Doctrine\ORM\EntityRepository
{
}
